export default {
  button: {
    bg_primary: '#47F',
    text_primary: '#FFF',
    bg_secondary: '#DDD',
    text_secondary: '#333',
    disabled: '#AAA',
  },
  white: 'whitesmoke',
  whiteTransparent: 'rgba(245,245,245,0.5)',
  whiteTranslucent: 'rgba(245,245,245,0.15)',
  black: '#070000',
  blackTransparent: 'rgba(7,0,0,0.75)',
  red: 'red',
  green: 'green',
  blue: 'blue',
  gray: '#777',
  grayLight: '#aaa',
  grayLighter: '#ccc',
  grayDark: '#333',
};
